In [56]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [58]:
df = pd.read_excel('Data_lab_w4.xlsx')
df

   id   X   Y
0   1   4  10
1   2  22  41
2   3  20  36
3   4   7  17
4   5  13  31
5   6  12  35
6   7  17  47
7   8   3  10
8   9   1   5
9  10  21  41

In [66]:
x = np.array(df['X']).reshape((-1, 1))
y = np.array(df['Y'])
model = LinearRegression().fit(x, y)
r_sq = model.score(x, y)
print(str(x.mean()) + '\n' + str(y.mean()) + '\n' + str(model.coef_) + '\n' + str(model.intercept_) + '\n' + str(r_sq))

12.0
27.3
[1.8202847]
5.456583629893242
0.8808245804605277

In [85]:
DATA = pd.read_csv("candy-data.csv", delimiter=',', index_col='competitorname')
DATA

,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,Y
competitorname,,,,,,,,,,,,,
100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,1
3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,1
One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,0
One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,0
Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Snickers Crisper,1,0,1,1,0,1,0,1,0,0.604,0.651,59.529251,1
Sour Patch Kids,0,1,0,0,0,0,0,0,1,0.069,0.116,59.863998,1
Sour Patch Tricksters,0,1,0,0,0,0,0,0,1,0.069,0.116,52.825947,1
Starburst,0,1,0,0,0,0,0,0,1,0.151,0.220,67.037628,1
Strawberry bon bons,0,1,0,0,0,0,1,0,1,0.569,0.058,34.578991,0

In [113]:
train_data = DATA.drop(['Caramel Apple Pops','Nestle Crunch'])
train_data

,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,Y
competitorname,,,,,,,,,,,,,
100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,1
3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,1
One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,0
One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,0
Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Snickers Crisper,1,0,1,1,0,1,0,1,0,0.604,0.651,59.529251,1
Sour Patch Kids,0,1,0,0,0,0,0,0,1,0.069,0.116,59.863998,1
Sour Patch Tricksters,0,1,0,0,0,0,0,0,1,0.069,0.116,52.825947,1
Starburst,0,1,0,0,0,0,0,0,1,0.151,0.220,67.037628,1
Strawberry bon bons,0,1,0,0,0,0,1,0,1,0.569,0.058,34.578991,0

In [73]:
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))
y = pd.DataFrame(train_data['winpercent'])

In [130]:
lr = LinearRegression().fit(X, y)

In [131]:
CarAppPops = DATA.loc['Caramel Apple Pops',:].to_frame().T

lr.predict(CarAppPops.drop(['winpercent', 'Y'], axis=1))

array([[54.29127151]])

In [125]:
NestleCrunch = DATA.loc['Nestle Crunch',:].to_frame().T

lr.predict(NestleCrunch.drop(['winpercent', 'Y'], axis=1))

array([[61.06849114]])

In [126]:
lr.predict([[0, 1, 1, 0, 0, 1, 0, 0, 0, 0.162, 0.71]])

array([[53.87339852]])