In [85]:
import pandas as pd
import numpy as np

In [97]:
df = pd.read_excel('ML_week2.xlsx')
df
#d = ((df['TARGET'] == 0) & (df['MIP'] >= 87.5859375) & (df['MIP'] <= 88.484375)).sum()

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TARGET
0,137.218750,45.390655,0.034985,0.134409,3.204013,17.177857,7.494588,74.003104,0
1,93.773438,41.883062,0.371402,1.291232,1.482441,12.959050,12.242911,180.158844,0
2,73.632812,35.461218,1.153607,4.161082,2.099498,13.057474,10.013591,140.894151,0
3,93.429688,39.883166,0.602060,1.518548,2.475753,14.146578,8.770640,107.970173,0
4,131.625000,44.111896,0.108905,0.239879,33.888796,70.398342,1.689460,1.031847,0
...,...,...,...,...,...,...,...,...,...
17893,121.117188,50.127279,-0.017936,-0.193900,1.566890,10.804730,13.737064,269.096109,0
17894,120.679688,40.918542,0.291465,0.627087,1.473244,13.912476,13.144044,203.416941,0
17895,138.101562,47.935314,-0.181827,-0.283746,3.270903,16.963817,6.988850,63.043499,0
17896,119.523438,44.198410,0.026662,0.352641,1.828595,12.674068,11.153939,166.582439,0
17897,154.875000,48.590766,-0.285643,0.129281,4.153010,21.971915,6.746838,52.230021,0

In [128]:
d = df.loc[(df['TARGET'] == 0) & (df['MIP'] >= 87.5859375) & (df['MIP'] <= 88.484375) | (df['TARGET'] == 1) & (df['MIP'] >= 101.9609375) & (df['MIP'] <= 115.3515625)]
#f = df.loc[(df['TARGET'] == 1) & (df['MIP'] >= 101.9609375) & (df['MIP'] <= 115.3515625)]
d

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC,TARGET
118,105.046875,47.085504,0.408034,0.331754,3.540970,26.129805,7.578517,57.367713,1
424,110.195312,54.475490,0.489785,-0.031921,19.280100,56.002144,2.875491,6.861892,1
465,88.250000,39.046047,0.571522,1.470493,4.650502,25.669724,6.217865,40.987388,0
523,105.500000,41.841778,0.417149,0.860093,2.082776,19.141674,10.146733,107.621655,1
596,109.328125,47.418534,0.274180,0.293365,5.330268,29.462131,5.969767,36.443420,1
...,...,...,...,...,...,...,...,...,...
17374,87.890625,37.659916,0.557335,1.823277,1.823579,13.115125,10.819064,151.921684,0
17385,87.742188,38.835037,0.854599,2.155629,4.173913,30.522729,7.192357,49.857458,0
17667,105.414062,47.067526,0.877089,0.891877,67.658027,89.168460,0.708237,-1.273890,1
17837,88.070312,41.152002,0.844845,1.296272,1.725753,11.726754,12.177619,206.719503,0
17840,88.101562,36.183093,0.587863,2.653011,3.885452,21.420056,7.255314,62.266004,0

In [131]:
d['MIP'].mean()

98.27386293316832

In [130]:
d.pop('TARGET')
d

,MIP,STDIP,EKIP,SIP,MC,STDC,EKC,SC
118,105.046875,47.085504,0.408034,0.331754,3.540970,26.129805,7.578517,57.367713
424,110.195312,54.475490,0.489785,-0.031921,19.280100,56.002144,2.875491,6.861892
465,88.250000,39.046047,0.571522,1.470493,4.650502,25.669724,6.217865,40.987388
523,105.500000,41.841778,0.417149,0.860093,2.082776,19.141674,10.146733,107.621655
596,109.328125,47.418534,0.274180,0.293365,5.330268,29.462131,5.969767,36.443420
...,...,...,...,...,...,...,...,...
17374,87.890625,37.659916,0.557335,1.823277,1.823579,13.115125,10.819064,151.921684
17385,87.742188,38.835037,0.854599,2.155629,4.173913,30.522729,7.192357,49.857458
17667,105.414062,47.067526,0.877089,0.891877,67.658027,89.168460,0.708237,-1.273890
17837,88.070312,41.152002,0.844845,1.296272,1.725753,11.726754,12.177619,206.719503
17840,88.101562,36.183093,0.587863,2.653011,3.885452,21.420056,7.255314,62.266004

In [132]:
d['MIP'].mean()

98.27386293316832

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [139]:
scaler = MinMaxScaler()
scaler.fit(d)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [140]:
d = scaler.transform(d)
d = pd.DataFrame(d)
d

,0,1,2,3,4,5,6,7
0,0.628869,0.502061,0.298218,0.191325,0.016369,0.189405,0.333466,0.084493
1,0.814294,0.761160,0.355354,0.124242,0.098691,0.511268,0.156702,0.012338
2,0.023917,0.220192,0.412479,0.401374,0.022172,0.184447,0.282326,0.061091
3,0.645189,0.318212,0.304588,0.288781,0.008742,0.114110,0.429992,0.156288
4,0.783061,0.513738,0.204668,0.184243,0.025728,0.225309,0.273001,0.054599
...,...,...,...,...,...,...,...,...
197,0.010974,0.171593,0.402564,0.466447,0.007386,0.049176,0.455262,0.219577
198,0.005627,0.212793,0.610320,0.527752,0.019680,0.236737,0.318952,0.073763
199,0.642093,0.501431,0.626038,0.294644,0.351726,0.868622,0.075246,0.000714
200,0.017445,0.294028,0.603503,0.369237,0.006875,0.034217,0.506323,0.297864
201,0.018571,0.119814,0.423900,0.619498,0.018171,0.138659,0.321318,0.091491

In [141]:
d[0].mean()

0.3849337240977674

In [43]:
STAR = [0.044, 0.086, 0.863, 0.91, 0.425, 0.991, 0.05, 0.527]
STAR

[0.044, 0.086, 0.863, 0.91, 0.425, 0.991, 0.05, 0.527]

In [122]:
ans = []
for j in range(202):
    sumTmp = 0
    for i in range(8):
        sumTmp += (STAR[i] - d[i][j]) ** 2
    tmp = sumTmp ** 0.5
    ans.append(tmp)
min(ans)

0.8109971245004225